### ISSUE TITLE
running acnnmain raises error

### ISSUE THREAD

**Issue by akhilsnair2017** [hczhai/PGOPT#2]
Hi,
I have been trying  for pt7 cluster generation according to the information given in the github page of PGOPT. After installation, when i run the "acnnmain pt7-gas.json" , the following error raises;

`read json: pt7-gas.json
Traceback (most recent call last):
  File "/home/akhil/softwares/PGOPT-PROGRAMS/ACNN/acnnmain", line 58, in <module>
    from utils.driver import Driver
  File "/home/akhil/softwares/PGOPT-PROGRAMS/ACNN/utils/driver.py", line 7, in <module>
    from parallel.main import ParallelRun
  File "/home/akhil/softwares/PGOPT-PROGRAMS/ACNN/parallel/main.py", line 1097
    except IOError, OSError:
                  ^
SyntaxError: invalid syntax
`
After checking the main.py file inside the 'parallel' directory and following your introduction, i think it is a problem with using python3.8 instead of python 2.7. May i know whether PGOPT code cannot be working with python 3 version?

**Comment by hczhai** [comment]
Hi, sorry, PGOPT does not support python3.
